nameOverride: "hippocraticai-api"
fullnameOverride: "hippocraticai-api"

## --- deployment
image:
  pullPolicy: Always
  repository: gcr.io/aleroxac/hippocraticai-api
  tag: NEW_IMAGE_TAG
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
livenessProbe: 
  httpGet:
    path: /health
    port: http
readinessProbe:
  httpGet:
    path: /health
    port: http
environment: {}
envFrom:
  - configMapRef:
      name: hippocraticai-api-config

## --- hpa
replicaCount: 1
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
      - type: Percent
        value: 20
        periodSeconds: 30
      - type: Pods
        value: 1
        periodSeconds: 30

## --- service
service:
  type: LoadBalancer
  port: 8000
